### ISSUE TITLE
Robot config max radius values not used

### ISSUE THREAD

**Issue by alwaystinkeringcom** [robdobsn/RBotFirmware#2]
xMaxMM and yMaxMM values from the robot config are read in MotionHelper.cpp, but never referenced. Increasing these values has no effect on motion calculations

**Comment by robdobsn** [comment]
These values were a hangover from previous code and have been removed
However the replacements for them (maxVal on each axis independently) had not been defined for SandTableScara so they have now been added

**Comment by grammesm** [comment]
I tried maxVal, and I'm still seeing the same problem. I have a pattern defined with a 190mm radius. Setting maxVal to 200, or 400, still produces the same result on the bot

**Comment by grammesm** [comment]
Fixed by setting maxVal for axis0 as the _TOTAL_ radius of the table, not just the length of one arm

**Comment by hackintoshlover** [comment]
Even after changing the values, it still does not work for me.
