### ISSUE TITLE
Home command in sequence does not finish

### ISSUE THREAD

**Issue by grammesm** [robdobsn/RBotFirmware#3]
Adding 'g28' to home the bot in a sequence of commands does not work.  The robot moves on to the next command before home finishes. This can be simulated by pressing home on the webUI, then starting a pattern before homing is complete

**Comment by robdobsn** [comment]
Should be fixed in current master branch. Please let me know if there's still an issue.

**Comment by grammesm** [comment]
Looks good to me!
